In [1]:
import pandas as pd
!pip install imblearn

Requirement already satisfied: imblearn in /opt/anaconda3/lib/python3.12/site-packages (0.0)
Requirement already satisfied: imbalanced-learn in /opt/anaconda3/lib/python3.12/site-packages (from imblearn) (0.12.3)
Requirement already satisfied: numpy>=1.17.3 in /opt/anaconda3/lib/python3.12/site-packages (from imbalanced-learn->imblearn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from imbalanced-learn->imblearn) (1.13.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /opt/anaconda3/lib/python3.12/site-packages (from imbalanced-learn->imblearn) (1.5.1)
Requirement already satisfied: joblib>=1.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from imbalanced-learn->imblearn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from imbalanced-learn->imblearn) (3.5.0)

In [2]:
df=pd.read_csv("/Users/ronak/Library/Containers/com.microsoft.Excel/Data/Downloads/CVD_cleaned 4.csv")

In [3]:
df.head()

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
0,Poor,Within the past 2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes,0.0,30.0,16.0,12.0
1,Very Good,Within the past year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No,0.0,30.0,0.0,4.0
2,Very Good,Within the past year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No,4.0,12.0,3.0,16.0
3,Poor,Within the past year,Yes,Yes,No,No,No,Yes,No,Male,75-79,180.0,93.44,28.73,No,0.0,30.0,30.0,8.0
4,Good,Within the past year,No,No,No,No,No,No,No,Male,80+,191.0,88.45,24.37,Yes,0.0,8.0,4.0,0.0

In [4]:
df.isnull().sum()

General_Health                  0
Checkup                         0
Exercise                        0
Heart_Disease                   0
Skin_Cancer                     0
Other_Cancer                    0
Depression                      0
Diabetes                        0
Arthritis                       0
Sex                             0
Age_Category                    0
Height_(cm)                     0
Weight_(kg)                     0
BMI                             0
Smoking_History                 0
Alcohol_Consumption             0
Fruit_Consumption               0
Green_Vegetables_Consumption    0
FriedPotato_Consumption         0
dtype: int64

In [5]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308854 entries, 0 to 308853
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   General_Health                308854 non-null  object
 1   Checkup                       308854 non-null  object
 2   Exercise                      308854 non-null  object
 3   Heart_Disease                 308854 non-null  object
 4   Skin_Cancer                   308854 non-null  object
 5   Other_Cancer                  308854 non-null  object
 6   Depression                    308854 non-null  object
 7   Diabetes                      308854 non-null  object
 8   Arthritis                     308854 non-null  object
 9   Sex                           308854 non-null  object
 10  Age_Category                  308854 non-null  object
 11  Height_(cm)                   308854 non-null  float64
 12  Weight_(kg)                   308854 non-null  float64
 13  BMI                           308854 non-null  float64
 14  Smoking_History               308854 non-null  object
 15  Alcohol_Consumption           308854 non-null  float64
 16  Fruit_Consumption             308854 non-null  float64
 17  Green_Vegetables_Consumption  308854 non-null  float64
 18  FriedPotato_Consumption       308854 non-null  float64
dtypes: float64(7), object(12)
memory usage: 44.8+ MB

In [6]:
df.shape

(308854, 19)

In [7]:
for col in df.columns:
    print(f"Column: {col}")
    print(df[col].unique())

Column: General_Health
['Poor' 'Very Good' 'Good' 'Fair' 'Excellent']
Column: Checkup
['Within the past 2 years' 'Within the past year' '5 or more years ago'
 'Within the past 5 years' 'Never']
Column: Exercise
['No' 'Yes']
Column: Heart_Disease
['No' 'Yes']
Column: Skin_Cancer
['No' 'Yes']
Column: Other_Cancer
['No' 'Yes']
Column: Depression
['No' 'Yes']
Column: Diabetes
['No' 'Yes' 'No, pre-diabetes or borderline diabetes'
 'Yes, but female told only during pregnancy']
Column: Arthritis
['Yes' 'No']
Column: Sex
['Female' 'Male']
Column: Age_Category
['70-74' '60-64' '75-79' '80+' '65-69' '50-54' '45-49' '18-24' '30-34'
 '55-59' '35-39' '40-44' '25-29']
Column: Height_(cm)
[150. 165. 163. 180. 191. 183. 175. 160. 168. 178. 152. 157. 188. 185.
 170. 173. 155. 193. 196. 206. 198. 140. 135. 145. 147. 142. 201. 218.
 124. 203. 137. 122. 216. 224. 229. 151. 177. 164. 162. 156. 153. 169.
 167. 172. 106. 190. 143. 171. 154. 176. 200. 146. 148. 158. 159. 187.
 104. 120. 107. 211. 226. 182. 213.  97. 184. 125. 127. 234. 130. 119.
 132. 105. 166. 181. 186.  91. 174. 208. 149.  96. 197. 161.  94. 103.
 221. 134. 144. 189. 100. 179. 117.  99. 102. 110. 241. 115. 205. 195.
 108.]
Column: Weight_(kg)
[ 32.66  77.11  88.45  93.44 154.22  69.85 108.86  72.57  91.63  74.84
  73.48  83.91 113.4   52.16 116.12  99.79  81.65 104.33  79.38  55.79
 124.74  81.19  70.31 112.49 147.42  84.82 102.06  64.41  60.78  61.23
  88.    90.72  49.9   85.28 120.2   69.4   62.14  65.77  89.81  66.68
  86.18  72.12  87.54  62.6   75.75  88.9   92.08  56.7   68.04  79.83
  63.5   58.97 114.76  45.36  73.94  54.43 125.19  77.56  96.16  95.25
 115.67  82.55 136.08  78.93  70.76  95.71  53.52  87.09  55.34  83.01
 123.38  98.88  73.03  76.66  97.52  71.67  83.46 122.47  58.06  74.39
  67.13  82.1   47.63  99.34  85.73 108.41  91.17  57.61  63.05  45.81
  94.35  44.45 117.93 107.5  127.01 106.59 107.95  89.36  92.99  53.07
  78.02 131.09  97.98  84.37 111.13  50.8   57.15  64.86  80.29  76.2
 114.31  65.32  97.07  67.59  75.3  105.69 110.68  86.64  51.26  61.69
 107.05  42.64  40.82 101.6   90.26 131.54  98.43  78.47  59.87  68.95
  60.33  94.8   48.53  96.62 117.48 102.51  46.27 109.77  58.51  68.49
 133.81 158.76  52.62  80.74  48.99 117.03  54.88  33.11  51.71  92.53
  34.02  44.91 105.23 145.6  106.14  56.25 139.71 124.28 103.42  71.21
 138.35 143.34 101.15 103.87 145.15  93.89  49.44  46.72 120.66 132.9
 112.04 167.83 142.88  66.22  63.96 162.39 176.9  121.56 111.58 136.98
 110.22 170.1  122.02 133.36 119.75 129.27 175.54 151.95 118.39 121.11
 132.45 135.62 119.29 102.97 172.37 156.49  43.09  43.54 157.4   59.42
 181.44 125.65 127.91 144.7  149.69 113.85 163.29 100.7  115.21 112.94
 208.65 127.46 100.24 136.53  50.35 130.63 122.92 141.97  47.17 142.43
 132.   118.84 116.57 151.5  137.44  72.   140.61 169.19  44.   160.57
 104.78 130.18  65.   134.72  48.08 139.25  53.98  36.29 129.73  38.56
 228.16 166.92 148.32 174.63 146.96 235.87 161.03 152.86 105.    75.
 109.   123.83 165.56  42.18 134.26 140.16 228.61 128.82  39.92  78.
 109.32 204.12  85.   141.52 161.48 185.97  90.    61.    95.    60.
  45.   126.1   82.   137.89  70.    64.   100.    63.   126.55 135.17
  74.   150.59  83.   189.15 143.79  97.    73.    54.    80.   164.2
  55.   155.13  52.    67.   144.24  68.   226.8   62.    76.   190.51
 146.51 188.24 199.58  79.    96.   152.41  58.   138.8  118.   165.11
 153.31  84.    38.1   41.73  39.01  37.19  87.   128.37 156.04 187.79
 168.28 136.    35.38 166.01 213.19  89.    66.    40.37  81.   210.92
  50.   155.58  25.4  224.53 179.17 159.66 176.45 209.56 151.05 148.78
 217.72 146.06 140.   219.99  86.   141.07 110.    92.    31.75  41.28
  33.57 130.    48.   161.93  94.    98.   183.25  53.    34.47 120.
  77.   183.7  272.16 171.46 206.84  26.76 200.    69.   101.   180.53
  47.   126.    59.   215.46 175.99 166.47 184.61 153.77  39.46 174.18
 186.43  46.    40.   195.04 104.   201.85 147.87 192.78  36.74 162.84
 134.   157.85 191.87 272.61  51.   231.33  37.65  93.    56.   149.23
 154.68 158.3  194.59 179.62 159.   210.47 180.98 169.64 285.76 177.81
 119.   150.   159.21 167.38 244.03 163.75 168.74 173.27 227.7   99.
 200.94 229.52 219.54 232.69 175.09 229.97 293.02 200.49 195.95 190.96
 212.73 150.14 229.06 178.72 181.89  34.93 171.   156.94 176.    57.
  71.   103.   254.01  30.84 249.48 240.4  238.14 205.93 273.52 215.
 187.33 182.   164.65 233.6   29.94 199.13 185.07 216.36 186.88 189.6
 173.73 219.09  24.95 203.21 210.01  35.83 190.06 116.   197.31 154.
 180.08 102.   222.26 202.76  27.22 206.38 135.   170.55 160.    43.
 188.69 106.   177.35 112.   160.12 195.   172.82 220.45 184.16 185.52
  26.31  41.   274.42 207.75 180.   175.   141.   230.88 222.71 258.55
 203.66 113.   182.34 195.5  191.42 215.91 178.26 257.64 244.94 263.08
 214.1  117.   172.   115.   185.   247.21  39.   193.68 127.    30.
 250.   252.2  283.5   49.    42.  ]
Column: BMI
[14.54 28.29 33.47 ... 63.83 19.09 56.32]
Column: Smoking_History
['Yes' 'No']
Column: Alcohol_Consumption
[ 0.  4.  3.  8. 30.  2. 12.  1.  5. 10. 20. 17. 16.  6. 25. 28. 15.  7.
  9. 24. 11. 29. 27. 14. 21. 23. 18. 26. 22. 13. 19.]
Column: Fruit_Consumption
[ 30.  12.   8.  16.   2.   1.  60.   0.   7.   5.   3.   6.  90.  28.
  20.   4.  80.  24.  15.  10.  25.  14. 120.  32.  40.  17.  45. 100.
   9.  99.  96.  35.  50.  56.  48.  27.  72.  36.  84.  26.  23.  18.
  21.  42.  22.  11. 112.  29.  64.  70.  33.  76.  44.  39.  75.  31.
  92. 104.  88.  65.  55.  13.  38.  63.  97. 108.  19.  52.  98.  37.
  68.  34.  41. 116.  54.  62.  85.]
Column: Green_Vegetables_Consumption
[ 16.   0.   3.  30.   4.  12.   8.  20.   1.  10.   5.   2.   6.  60.
  28.  25.  14.  40.   7.  22.  24.  15. 120.  90.  19.  13.  11.  80.
  27.  17.  56.  18.   9.  21.  99.  29.  31.  45.  23. 100. 104.  32.
  48.  75.  36.  35. 112.  26.  50.  33.  96.  52.  76.  84.  34.  97.
  88.  98.  68.  92.  55.  95.  64. 124.  61.  65.  77.  85.  44.  39.
  70.  93. 128.  37.  53.]
Column: FriedPotato_Consumption
[ 12.   4.  16.   8.   0.   1.   2.  30.  20.  15.  10.   3.   7.  28.
   5.   9.   6. 120.  32.  14.  60.  33.  48.  25.  24.  21.  90.  13.
  99.  17.  18.  40.  56.  34.  36.  44. 100.  11.  64.  45.  80.  29.
  68.  26.  50.  22.  95.  23.  27. 112.  35.  31.  98.  96.  88.  92.
  19.  76.  49.  97. 128.  41.  37.  42.  52.  72.  46. 124.  84.]

In [8]:

df.columns = df.columns.str.lower().str.replace(" ", "_")
df.rename(columns = {'height_(cm)' : 'height', 'weight_(kg)' : 'weight', 'green_vegetables_consumption' : 'vegetables_consumption', 'friedpotato_consumption' : 'potato_consumption'}, inplace = True)

In [9]:
df['checkup'] = df['checkup'].replace('Within the past 2 years', 'Past 2 years')
df['checkup'] = df['checkup'].replace('Within the past year', 'Past 1 year')
df['checkup'] = df['checkup'].replace('Within the past 5 years', 'Past 5 years')
df['checkup'] = df['checkup'].replace('5 or more years ago', 'More than 5 years')
df['diabetes'] = df['diabetes'].replace('No, pre-diabetes or borderline diabetes', 'No Pre Diabetes')
df['diabetes'] = df['diabetes'].replace('Yes, but female told only during pregnancy', 'Only during pregnancy')
df['age_category'] = df['age_category'].replace('18-24', 'Young')
df['age_category'] = df['age_category'].replace('25-29', 'Adult')
df['age_category'] = df['age_category'].replace('30-34', 'Adult')
df['age_category'] = df['age_category'].replace('35-39', 'Adult')
df['age_category'] = df['age_category'].replace('40-44', 'Mid-Aged')
df['age_category'] = df['age_category'].replace('45-49', 'Mid-Aged')
df['age_category'] = df['age_category'].replace('50-54', 'Mid-Aged')
df['age_category'] = df['age_category'].replace('55-59', 'Senior-Adult')
df['age_category'] = df['age_category'].replace('60-64', 'Senior-Adult')
df['age_category'] = df['age_category'].replace('65-69', 'Elderly')
df['age_category'] = df['age_category'].replace('70-74', 'Elderly')
df['age_category'] = df['age_category'].replace('75-79', 'Elderly')
df['age_category'] = df['age_category'].replace('80+', 'Elderly')

EDA & Data Preprocessing

In [10]:

BMI_bins = [13, 19, 28, 33, 40, 100]
BMI_labels = ['Underweight', 'Normal weight', 'Overweight', 'Obese I', 'Obese II']
df['bmi_group'] = pd.cut(df['bmi'], bins=BMI_bins, labels=BMI_labels, right=False)

In [11]:
col_mov = df.pop('bmi_group')
df.insert(14, 'bmi_group', col_mov)

In [12]:
df['bmi_group'] = df['bmi_group'].astype('object')

In [13]:
from sklearn.preprocessing import OneHotEncoder
# Convert 'heart_disease' to numeric
df['heart_disease'] = df['heart_disease'].map({'Yes': 1, 'No': 0})

# One-hot encode categorical columns
cat = ['sex', 'smoking_history']
df = pd.get_dummies(df, columns=cat, drop_first=False)

In [14]:
from sklearn.preprocessing import LabelEncoder
categorical_col = ['general_health', 'checkup', 'exercise', 'skin_cancer', 'other_cancer', 'depression', 'diabetes', 'arthritis', 'age_category', 'bmi_group']


label_encoder = LabelEncoder()
for col in categorical_col:
    df[col] = label_encoder.fit_transform(df[col])

In [15]:
df.head()

,general_health,checkup,exercise,heart_disease,skin_cancer,other_cancer,depression,diabetes,arthritis,age_category,...,bmi,bmi_group,alcohol_consumption,fruit_consumption,vegetables_consumption,potato_consumption,sex_Female,sex_Male,smoking_history_No,smoking_history_Yes
0,3,3,0,0,0,0,0,0,1,1,...,14.54,4,0.0,30.0,16.0,12.0,True,False,False,True
1,4,2,0,1,0,0,0,3,0,1,...,28.29,3,0.0,30.0,0.0,4.0,True,False,True,False
2,4,2,1,0,0,0,0,3,0,3,...,33.47,1,4.0,12.0,3.0,16.0,True,False,True,False
3,3,2,1,1,0,0,0,3,0,1,...,28.73,3,0.0,30.0,30.0,8.0,False,True,True,False
4,2,2,0,0,0,0,0,0,0,1,...,24.37,0,0.0,8.0,4.0,0.0,False,True,False,True

In [18]:

X = df.drop("heart_disease", axis = 1)
y = df['heart_disease']

In [20]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_balanced, y_balanced = smote.fit_resample(X, y)

print("Before SMOTE:", y.value_counts())
print("After SMOTE:", y_balanced.value_counts())

Before SMOTE: heart_disease
0    283883
1     24971
Name: count, dtype: int64
After SMOTE: heart_disease
0    283883
1    283883
Name: count, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X_balanced, y_balanced, test_size=0.3, random_state=42)

In [22]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

In [23]:
print(X_train_scaled)

[[-1.58937885  3.41842437  0.780051   ... -1.17709639 -1.25780008
   0.84175395]
 [ 1.4822562  -0.12233858  0.780051   ... -1.17709639  0.79503891
  -1.18799561]
 [-0.05356133 -0.12233858  0.780051   ... -1.17709639 -1.25780008
   0.84175395]
 ...
 [-0.05356133 -0.12233858 -1.28196745 ...  0.8495481   0.79503891
   0.84175395]
 [-0.82147009  1.64804289 -1.28196745 ...  0.8495481   0.79503891
  -1.18799561]
 [ 1.4822562   1.64804289  0.780051   ...  0.8495481   0.79503891
  -1.18799561]]

In [24]:
# Create the models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

LR = LogisticRegression()
RFC= RandomForestClassifier()
XGB = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)

# Fit the models
LR.fit(X_train_scaled, y_train)
RFC.fit(X_train_scaled, y_train)
XGB.fit(X_train_scaled, y_train)

# Make predictions
Lr_pred = LR.predict(X_test_scaled)
Rf_pred = RFC.predict(X_test_scaled)
Xgb_pred= XGB.predict(X_test_scaled)

/opt/anaconda3/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [21:04:50] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [25]:
from sklearn.metrics import classification_report, roc_auc_score
lr_d_report = classification_report(y_test, Lr_pred)

rf_d_report = classification_report(y_test, Rf_pred)

xgb_d_report=classification_report(y_test,Xgb_pred )


print("="*40, "Logistic regression report:", "="*45, '\n')
print(lr_d_report)



print("="*40, "Random forest report:", "="*45, '\n')
print(rf_d_report)

print("="*40, "XGBClassifier", "="*45, '\n')
print(rf_d_report)

======================================== Logistic regression report: =============================================

              precision    recall  f1-score   support

           0       0.77      0.87      0.82     85071
           1       0.86      0.74      0.80     85259

    accuracy                           0.81    170330
   macro avg       0.81      0.81      0.81    170330
weighted avg       0.81      0.81      0.81    170330

======================================== Random forest report: =============================================

              precision    recall  f1-score   support

           0       0.93      0.96      0.94     85071
           1       0.96      0.92      0.94     85259

    accuracy                           0.94    170330
   macro avg       0.94      0.94      0.94    170330
weighted avg       0.94      0.94      0.94    170330

======================================== XGBClassifier =============================================

              precision    recall  f1-score   support

           0       0.93      0.96      0.94     85071
           1       0.96      0.92      0.94     85259

    accuracy                           0.94    170330
   macro avg       0.94      0.94      0.94    170330
weighted avg       0.94      0.94      0.94    170330